---
- name: Running Docker
  hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: pull an image
      docker_image:
        name: harishpallapu/jmeter-3i:latest
      docker_container:
        name: jmeter
        image: harishpallapu/jmeter-3i:latest
        state: started
      file:
        path: /jmeter/bin/project
        state: directory


   
