---
- name: Running Docker
  hosts: all
  become: false
  gather_facts: false
  tasks:

   - name: pull an image
     delegate_to: localhost
     docker_image:
       name: harishpallapu/jmeter-3i:latest
