---
- name: Running Docker
  hosts: all
  become: true
  gather_facts: false
  tasks:
  
    - name: pull an image
      shell: |
        docker start -it jmeter /bin/bash       
        docker exec -it jmeter /bin/bash
