---
- name: Running Docker
  hosts: all
  become: true
  gather_facts: false
  tasks:
  
    - name: pull an image
      shell: |
        docker run -it --name jmeter -w /jmeter/bin/project -v /root:/jmeter/bin/project harishpallapu/jmeter-3i:latest
        git clone https://github.com/Poornateja2509/NRTC_JMeter.git
        sh /jmeter/bin/jmeter -n -t *.jmx -l result.jtl -e -o result.html 

     

