---
- name: Running Docker
  hosts: all
  become: true
  gather_facts: false
  tasks:
  
    - name: pull an image
      shell: |
        docker run -it --name jmeter harishpallapu/jmeter-3i
        docker start jmeter       
        
